DROP TABLE IF EXISTS scooter_records;

CREATE TABLE scooter_records {
	id SERIAL PRIMARY KEY,
	company VARCHAR(10),
	last_updated BIGINT,
	bike_id TEXT,
	tractid BIGINT
};

CREATE TABLE weather_records (
	id SERIAL PRIMARY KEY,
	AIRTEMP VARCHAR(10),
	RELATIVEHUMIDITY VARCHAR(10),
	VISIBILITY VARCHAR(10),
	WINDSPEED VARCHAR(10),
	DATADATETIME BIGINT,
	tractid BIGINT
);

CREATE TABLE process_log (
	id SERIAL PRIMARY KEY,
	last_saved BIGINT,
	saved_records INTEGER
);


